name: Push to Public Repository

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push-to-public:
    if: ${{ github.repository == 'gmo-internet/priv_conoha_vps_openapi' }}
    uses: gmo-internet/priv_share/.github/workflows/publish.yml@main
    secrets: inherit
